web:
  image: debian:jessie
  tty: true
  volumes:
    - ./schema:/schema
    - ./html:/usr/share/nginx/html
satis:
  build: satis
  volumes:
    - /satis
  volumes_from:
    - web
nginx:
  image: nginx
  volumes_from:
    - web
  ports:
    - 80:80
cron:
  build: cron
  volumes_from:
    - satis
    - web
